version: '3.7'
services:

#############
### FRONT ###
#############

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    image: web.lab_monitor
    container_name: web.lab_monitor
    ports:
    - 80:80
    environment:
      PORT: 80
      DEBUG: "False"
      API_TEMPERATURE_HOST: api_temperature
      API_TEMPERATURE_PORT: 80
    volumes:
    - ./web/html:/usr/share/nginx/html/:z

    depends_on:
    - api_temperature


###################
### temperature ###
###################

  api_temperature:
    build:
      context: ./api_temperature
      dockerfile: Dockerfile
    image: api_temperature.lab_monitor
    container_name: api_temperature.lab_monitor
    ports:
    - 8100:80
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_USER: root
      MONGO_PASS: example
      PORT: 80
      DEBUG: "True"
      IGNORE_CACHE: "False"
    volumes:
    - ./api_temperature/src:/src
    depends_on:
    - mongo 


#############
### mongo ###
#############

  mongo:
    image: mongo:4.2.3
    container_name: mongo.lab_monitor
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017

  mongo_express:
    image: mongo-express
    container_name: mongo_express.lab_monitor
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    ports:
      - 8081:8081
    depends_on:
    - mongo  

